### ISSUE TITLE
Remove .vscode folder

### ISSUE THREAD

**Issue by StefanoMagrassi** [PolymerX/postcss-polymer-loader#3]
Remove `.vscode` folder from the repo

**Comment by StefanoMagrassi** [comment]
@equinusocio `.vscode` is a folder for the editor configuration, based on the developer specific settings.

The directory will be *giti-gnored*, so you can keep your particular settings

**Comment by equinusocio** [comment]
@StefanoMagrassi Yes `iKnow`. My 👎 was for who versioned this folder

**Comment by LasaleFamine** [comment]
I'm not agreeing with this.
I want to share this specific configuration with who will develop the tool since I think it will be a good help. There is XO enable inside and nothing more. The versioning of this file was specifically wanted.

**Comment by StefanoMagrassi** [comment]
The `xo: enabled` setting is specific to your VSCode configuration (you installed the plugin, other people may not have installed it).

The `.vscode` folder should be versioned only if there are any plugin/setting required for the development/building process

**Comment by LasaleFamine** [comment]
I know the setting is related to VSCode (this is why the folder is called .vscode :D) and this is exactly what I want: having the configuration for VSCode ready when I clone the repo. This is just one thing, but I use also other configurations that I can add in the future. 

By the way, I don't agree with the fact that should be versioned ONLY for that situations you listed.
Quoting Pasero from the Stackoverflow answer:
> Check in the .vscode folder if you want to share settings, task configuration and debug configuration with the team. I think generally it makes sense to share settings (e.g. whitespace vs tabs) with the team if you want to enforce settings in a team. 

I know also that the .editorconfig is the other main cross-editor configuration, but this is a specific configuration that I think should be present.

**Comment by StefanoMagrassi** [comment]
> having the configuration for VSCode ready when I clone the repo

But it's not your personal repo and, as you said, the `.editorconfig` or other tools (like .rc files) are in place when you need to share some kind of configuration.

If I use a particular plugin and its settings are saved in the .vscode folder, I will force other developers to use them, even if the features that plugin provides are not part of or necessary for the project.

I'm not saying that the .vscode folder should be ignored **always**, but until it is indispensable

**Comment by LasaleFamine** [comment]
> But it's not your personal repo and, as you said, the .editorconfig or other tools (like .rc files) are in place when you need to share some kind of configuration.

It's not personal just because is open sourced? Of course is personal, I made it! And I want other developers to know about the XO plugin of VSCode since is a really nice to have, also if you forgot to run XO as command and also because I want this to be a common practice within my projects.

> If I use a particular plugin and its settings are saved in the .vscode folder, I will force other developers to use them, even if the features that plugin provides are not part of or necessary for the project.

This is not true. You can have the configuration enable without having the plugins and nothing will change for you.

**Comment by LasaleFamine** [comment]
> Yep, or better saying, it's not strictly personal because of it's purpose (and also because you published it under an organization). I think these are "personal projects"

I'm afraid that answering this will bring us in an off-topic field. So let's keep this for another place ;D

> In this case, if xo is an important part of the project, make it mandatory when building/testing (as you already did).

So I have to make mandatory also the `.vscode` folder. 🚀

**Comment by StefanoMagrassi** [comment]
> So I have to make mandatory also the .vscode folder. 🚀

why?

**Comment by LasaleFamine** [comment]
It's explained on earlier posts!
Closing this since I think I want to maintain the repo with the `.vscode` versioned.
